package com.agileapes.dragonfly.model;

import java.util.HashSet;
import java.util.Set;

/**
 * @author Mohammad Milad Naseri (m.m.naseri@gmail.com)
 * @since 1.0 (2013/9/14, 4:05)
 */
public class EntityHandlerModel {

    private final Set<PropertyAccessModel> properties = new HashSet<PropertyAccessModel>();
    private Class<?> entityType;
    private PropertyAccessModel key = null;
    private boolean keyAutoGenerated = false;

    public Set<PropertyAccessModel> getProperties() {
        return properties;
    }

    public Class<?> getEntityType() {
        return entityType;
    }

    public void setEntityType(Class<?> entityType) {
        this.entityType = entityType;
    }

    public void addProperty(PropertyAccessModel property) {
        properties.add(property);
    }

    public PropertyAccessModel getKey() {
        return key;
    }

    public void setKey(PropertyAccessModel key) {
        this.key = key;
    }

    public boolean isKeyAutoGenerated() {
        return keyAutoGenerated;
    }

    public void setKeyAutoGenerated(boolean keyAutoGenerated) {
        this.keyAutoGenerated = keyAutoGenerated;
    }
}
